apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ptt-deployment
build:
  artifacts:
  - image: ghcr.io/2023-da-ptt/ptt-backend
    context: backend
    docker:
      dockerfile: src/main/docker/Dockerfile.jvm
  - image: ghcr.io/2023-da-ptt/ptt-frontend
    context: frontend
    docker:
      dockerfile: Dockerfile.skaffold
  - image: ghcr.io/2023-da-ptt/ptt-test-environment
    context: test-env
    docker:
      dockerfile: src/main/docker/Dockerfile.jvm
deploy:
  kubectl:
    manifests:
    - backend/k8s/deployment.yml
    - backend/k8s/postgres-persistent-volume.yml
    - backend/k8s/postgres-secret.yml
    - backend/k8s/service.yml
    - frontend/k8s/deployment.yml
    - frontend/k8s/service.yml
    - test-env/k8s/deployment.yml
    - test-env/k8s/service.yml
portForward:
- resourceType: service
  resourceName: ptt-frontend-service
  namespace: ptt
  port: 80
  localPort: 8080
- resourceType: service
  resourceName: ptt-backend-service
  namespace: ptt
  port: 8080
  localPort: 8081
- resourceType: service
  resourceName: ptt-mqtt-service
  namespace: ptt
  port: 1883
  localPort: 1883
- resourceType: service
  resourceName: ptt-mqtt-service
  namespace: ptt
  port: 9001
  localPort: 9001