apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ptt-deployment
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: ghcr.io/2023-da-ptt/ptt-backend
    context: backend
    docker:
      dockerfile: src/main/docker/Dockerfile.dev
    sync:
      manual:
       - src: 'src/**/*'
         dest: /usr/src/app
       - src: 'pom.xml'
         dest: /usr/src/app
  - image: ghcr.io/2023-da-ptt/ptt-client
    context: client
    docker:
      dockerfile: src/main/docker/Dockerfile.jvm
  - image: ghcr.io/2023-da-ptt/ptt-frontend
    context: frontend
    docker:
      dockerfile: Dockerfile.dev
    sync:
      manual:
       - src: '**/*'
         dest: /usr/src/app
  - image: ghcr.io/2023-da-ptt/ptt-test-environment
    context: test-env
    docker:
      dockerfile: src/main/docker/Dockerfile.jvm
    sync:
      manual:
       - src: 'src/**/*'
         dest: /usr/src/app
       - src: 'pom.xml'
         dest: /usr/src/app
deploy:
  helm:
    releases:
    - name:	backend
      chartPath: ./backend/helm
      artifactOverrides:
        image: ghcr.io/2023-da-ptt/ptt-backend
      imageStrategy:
        helm: {}
    - name:	frontend
      chartPath: ./frontend/helm
      artifactOverrides:
        image: ghcr.io/2023-da-ptt/ptt-frontend
      imageStrategy:
        helm: {}
    - name:	test-env
      chartPath: ./test-env/helm
      artifactOverrides:
        image: ghcr.io/2023-da-ptt/ptt-test-environment
      imageStrategy:
        helm: {}
portForward:
- resourceType: service
  resourceName: ptt-frontend-service
  namespace: ptt
  port: 80
  localPort: 8080
- resourceType: service
  resourceName: ptt-backend-service
  namespace: ptt
  port: 8080
  localPort: 8081
- resourceType: deployment
  resourceName: ptt-backend
  namespace: ptt
  port: 5005
  localPort: 5005
- resourceType: deployment
  resourceName: ptt-backend
  namespace: ptt
  port: 5432
  localPort: 5432
- resourceType: service
  resourceName: ptt-test-environment-service
  namespace: ptt
  port: 8080
  localPort: 8082
- resourceType: service
  resourceName: ptt-mqtt-service
  namespace: ptt
  port: 1883
  localPort: 1883
- resourceType: service
  resourceName: ptt-mqtt-service
  namespace: ptt
  port: 9001
  localPort: 9001