apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ptt-deployment
build:
  artifacts:
  - image: 2023-da-ptt/ptt-backend
    context: backend
    buildpacks:
      builder: codejive/buildpacks-quarkus-builder:jvm
  - image: 2023-da-ptt/ptt-frontend
    context: frontend
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: 2023-da-ptt/ptt-test-environment
    context: test-env
    buildpacks:
      builder: codejive/buildpacks-quarkus-builder:jvm
deploy:
  kubectl:
    manifests:
    - backend/k8s/deployment.yml
    - backend/k8s/ingress.yml
    - backend/k8s/postgres-persistent-volume.yml
    - backend/k8s/postgres-secret.yml
    - backend/k8s/service.yml
    - frontend/k8s/deployment.yml
    - frontend/k8s/ingress.yml
    - frontend/k8s/service.yml
    - test-env/k8s/deployment.yml
    - test-env/k8s/ingress.yml
    - test-env/k8s/service.yml